/**
 * Better Auth's tables, as a migration, when `src/api/auth.ts` changes:
 *
 *   bun run auth:schema <name>
 *
 * Replays every migration in `src/api/migrations` into an in-memory SQLite
 * database, asks Better Auth what its options still need there, and writes
 * that as a new drizzle-kit custom migration (`<ts>_auth-<name>`), so it
 * takes its place in the chain `Drizzle.Schema` and the database apply.
 * Better Auth's tables are not in `src/api/schema.ts`: Drizzle never diffs
 * them, this does. Review the SQL before committing.
 */
import { Database } from "bun:sqlite";
import { readdir } from "node:fs/promises";
import { getMigrations } from "better-auth/db/migration";
import { authOptions } from "../src/api/auth.ts";

const MIGRATIONS = new URL("../src/api/migrations/", import.meta.url);

const name = process.argv[2];

if (name === undefined || !/^[a-z0-9-]+$/.test(name)) {
  console.error("usage: bun run auth:schema <name>   (lowercase words and dashes)");
  process.exit(1);
}

const migrations = async () => (await readdir(MIGRATIONS.pathname)).filter((entry) => /^\d{14}_/.test(entry)).sort();

const db = new Database(":memory:");

for (const migration of await migrations()) {
  // drizzle-kit's `--> statement-breakpoint` markers are SQL comments.
  db.exec(await Bun.file(new URL(`${migration}/migration.sql`, MIGRATIONS)).text());
}

const options = authOptions(db, "schema-only-secret-not-used-for-anything", "http://localhost");

// Nothing to do compiles to a lone ";".
const statements = (await (await getMigrations(options)).compileMigrations())
  .split(";")
  .map((statement) => statement.trim())
  .filter((statement) => statement !== "")
  .map((statement) => `${statement};`);

if (statements.length === 0) {
  console.log("Better Auth's tables already match src/api/auth.ts: nothing to write.");
  process.exit(0);
}

const before = new Set(await migrations());

const generated = Bun.spawnSync(
  ["bunx", "drizzle-kit", "generate", "--custom", "--dialect", "sqlite", "--schema", "./src/api/schema.ts", "--out", "./src/api/migrations", "--name", `auth-${name}`],
  { stdout: "inherit", stderr: "inherit" },
);

const created = (await migrations()).filter((migration) => !before.has(migration));

if (generated.exitCode !== 0 || created.length !== 1) {
  console.error("drizzle-kit did not create exactly one custom migration");
  process.exit(1);
}

const target = new URL(`${created.join("")}/migration.sql`, MIGRATIONS);

await Bun.write(
  target,
  `-- Generated by scripts/auth-schema.ts from src/api/auth.ts. Review before committing.\n${statements.join("\n--> statement-breakpoint\n")}\n`,
);

console.log(`wrote ${target.pathname} (${statements.length} statements)`);
