/**
 * Compile Better Auth's schema for Ficus's options into a D1 migration:
 *
 *   bun run auth:schema
 *
 * Migrates an empty in-memory SQLite database and writes the SQL it took to
 * `src/api/migrations/0001_auth.sql`. Run it when `src/api/auth.ts` changes
 * plugins; review the diff; add a new numbered file for an existing database
 * rather than editing an applied one.
 */
import { Database } from "bun:sqlite";
import { getMigrations } from "better-auth/db/migration";
import { authOptions } from "../src/api/auth.ts";

const options = authOptions(new Database(":memory:"), "schema-only-secret-not-used-for-anything", "http://localhost");

const { compileMigrations } = await getMigrations(options);

const sql = await compileMigrations();

const target = new URL("../src/api/migrations/0001_auth.sql", import.meta.url);

await Bun.write(target, `-- Generated by scripts/auth-schema.ts from src/api/auth.ts. Do not edit.\n${sql}\n`);

console.log(`wrote ${target.pathname} (${sql.split(";").length - 1} statements)`);
